name: common_test
description: Package for common utilities used in testing
version: 1.0.0
publish_to: "none"
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.3

# Add regular dependencies here.
dependencies:
  common:
    path: ../common
  mocktail: ^1.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
