name: common_test_support
description: Common test support
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.3

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  dependencies_test_support:
    path: ../../dependencies/test_support
  common:
    path: ..
  flutter_test:
    sdk: flutter

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
